openapi: 3.0.1
info:
  title: addressstringchecklength
  description: API Definition of HelloWorld
  version: 1.0.0
servers:
- url: http://localhost:8290/addressstringchecklength
paths:
  /:
    get:
      responses:
        default:
          description: Default response
