openapi: 3.0.1
info:
  title: xslt
  description: API Definition of xslt
  version: 1.0.0
servers:
- url: http://localhost:8290/xslt
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
